# Generated by Django 5.0.1 on 2024-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_guide_phone_number_tour_guide_years_lived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_guide',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Home Town'),
        ),
        migrations.AlterField(
            model_name='tour_guide',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tour_guide',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='tour_guide',
            name='state',
            field=models.CharField(default='', max_length=200, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Home Town'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='dates_in_town',
            field=models.CharField(default='', max_length=200, verbose_name='Dates in Town'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone_number',
            field=models.CharField(default=0, max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='state',
            field=models.CharField(default='', max_length=200, verbose_name='State'),
        ),
    ]
