# Generated by Django 5.0.2 on 2024-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_guide_likes_alter_tour_guide_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_guide',
            name='tourists',
            field=models.ManyToManyField(related_name='guide', to='tours.tourist'),
        ),
    ]
