# Generated by Django 5.0.2 on 2024-02-24 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_guide_tourists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_guide',
            name='tourists',
        ),
        migrations.CreateModel(
            name='Acceptances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('tour_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_relations', to='tours.tour_guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_guide_relations', to='tours.tourist')),
            ],
        ),
    ]
