# Generated by Django 5.0.2 on 2024-02-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tour_guide_tourists_acceptances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.activity')),
                ('tour_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour_guide')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourist')),
            ],
            options={
                'unique_together': {('tour_guide', 'activity'), ('tourist', 'activity')},
            },
        ),
        migrations.AddField(
            model_name='tour_guide',
            name='activities',
            field=models.ManyToManyField(related_name='tour_guides', through='tours.Liked_Activities', to='tours.activity'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='activities',
            field=models.ManyToManyField(related_name='tourists', through='tours.Liked_Activities', to='tours.activity'),
        ),
    ]
