# Generated by Django 5.0.2 on 2024-02-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_activity_liked_activities_tour_guide_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_guide',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='likes',
        ),
    ]
